[supervisord]
nodaemon=true
loglevel=info
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[group:laravel-worker]
priority=999
programs=laravel-queue

[program:laravel-queue]
numprocs=3
autostart=true
autorestart=true
redirect_stderr=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/log/supervisor/queue.log
command=php /var/www/artisan queue:work redis --sleep=3 --tries=3