max_execution_time = 60
max_input_time =-1
post_max_size = 300M
upload_max_filesize = 250M
memory_limit=2000M
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.revalidate_freq=60
opcache.fast_shutdown=1
opcache.jit_buffer_size=256M
opcache.jit=1255
;memprof.output_dir="~/Desktop/memprof"