[supervisord]
nodaemon=true
loglevel=info
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:octane]
process_name=%(program_name)s
command=/usr/local/bin/php /var/www/artisan octane:start --server=swoole --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/octane.log
stderr_logfile=/var/www/storage/logs/octane_error.log

[program:horizon]
process_name=%(program_name)s
command=/usr/local/bin/php /var/www/artisan horizon
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/horizon.log
stderr_logfile=/var/www/storage/logs/horizon_error.log